import { EllipsisVertical, MapPin } from "lucide-react";
import { SiteActionsMenu } from "./SiteActionsMenu";
import type { Site } from "./types";

type Props = { sites: Site[]; openMenuId: string | null; onToggleMenu: (id: string) => void; onView: (site: Site) => void; onEdit: (site: Site) => void; onManageClients: (site: Site) => void; onToggleStatus: (site: Site) => void; onDelete: (site: Site) => void; };

export function SitesTable({ sites, openMenuId, onToggleMenu, onView, onEdit, onManageClients, onToggleStatus, onDelete }: Props) {
  return <div className="mt-5 overflow-visible rounded-xl border border-slate-200"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200"><tr>{["Site Name", "Site Code", "Address", "Client", "Assigned Guards", "Status", "Actions"].map((heading) => <th key={heading} className="px-3 py-4 font-medium">{heading}</th>)}</tr></thead><tbody>{sites.map((site) => <tr key={site.id} className="border-b border-slate-200 last:border-0"><td className="px-3 py-5 font-medium"><span className="flex items-center gap-2"><MapPin className="size-4 text-slate-400" />{site.name}</span></td><td>{site.code}</td><td>{site.address}</td><td className="max-w-48 truncate">{site.clients?.length ? site.clients.map((client) => client.name).join(", ") : "-"}</td><td>{site.assignedGuards}</td><td><span className={site.status === "ACTIVE" ? "rounded-xl bg-emerald-100 px-3 py-1 text-xs text-emerald-700" : "rounded-xl bg-slate-100 px-3 py-1 text-xs text-slate-600"}>{site.status === "ACTIVE" ? "Active" : "Inactive"}</span></td><td className="relative"><button type="button" onClick={(event) => { event.stopPropagation(); onToggleMenu(site.id); }}><EllipsisVertical className="size-5" /></button>{openMenuId === site.id && <div onClick={(event) => event.stopPropagation()}><SiteActionsMenu site={site} onView={() => onView(site)} onEdit={() => onEdit(site)} onManageClients={() => onManageClients(site)} onToggleStatus={() => onToggleStatus(site)} onDelete={() => onDelete(site)} /></div>}</td></tr>)}</tbody></table></div>;
}
