import { CalendarDays, Clock3, Globe2, MapPin, Ruler, X } from "lucide-react";
import type { Site } from "./types";

const guards = ["Amir Khan", "Au Chee Tack", "Das Tilak Chanda", "Edmund Au Chee Wee", "Gary Leong", "Hannah Tan", "Isaac Lim", "Jamal Rahman", "Khalid Ahmed", "Lina Wong", "Mohamed Faisal", "Nadia Binte", "Omar Syed", "Priya Nair", "Ravi Kumar", "Siti Aisyah", "Tan Wei Ming", "Umar Farooq", "Vijay Kumar", "Zara Ali"];

export function SiteDetailsModal({ site, onClose }: { site: Site; onClose: () => void }) {
  const active = site.status === "ACTIVE";
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" aria-label={`${site.name} details`} className="max-h-[95vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-5 text-sm shadow-2xl sm:p-7"><header className="flex items-start justify-between"><div><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-xl bg-slate-100"><MapPin className="size-6 text-slate-600" /></span><h2 className="text-xl font-bold text-slate-950">{site.name}</h2></div><p className="mt-3 text-sm text-slate-500">Site Code: {site.code} | <Status active={active} /></p></div><button type="button" onClick={onClose} aria-label="Close details" className="rounded-md border border-slate-300 p-1 text-slate-500 hover:bg-slate-50"><X className="size-5" /></button></header><div className="mt-6 grid gap-4 md:grid-cols-2"><Card title="Site Information"><InfoGrid items={[["Name", site.name], ["Code", site.code], ["Status", active ? "Active" : "Inactive"]]} status={active} /></Card><Card title="Location Details"><InfoGrid items={[["Address", site.address], ["Latitude", site.latitude || "1.319183"], ["Longitude", site.longitude || "103.8198"]]} /></Card><Card title="Configuration"><div className="grid grid-cols-2 gap-x-6 gap-y-5"><Value icon={<Globe2 />} label="Timezone" value="Asia/Singapore" /><Value icon={<Ruler />} label="Geofence" value="10000m" /><Value icon={<CalendarDays />} label="Created" value="29/05/2026" /><Value icon={<Clock3 />} label="Updated" value="28/08/2026" /></div></Card><Card title="Client Information"><p className="text-slate-500">No clients assigned to this site</p></Card><Card title="Assigned Guards" badge="20 Guards"><p className="mb-4 text-slate-500">Guards with access to this site</p><div className="max-h-60 space-y-3 overflow-y-auto pr-3">{guards.map((name, index) => <Guard key={name} name={name} index={index} />)}</div></Card><Card title="Recent Activity"><p className="mb-4 text-slate-500">Latest events and updates for this site</p><div className="space-y-3"><Activity label="Site created" date="29/05/2026 09:33:12 AM" green /><Activity label="Last updated" date="28/08/2026 03:05:20 PM" /></div></Card></div></section></div>;
}

function Status({ active }: { active: boolean }) { return <span className={active ? "rounded-lg bg-emerald-100 px-3 py-1 text-xs text-emerald-700" : "rounded-lg bg-slate-100 px-3 py-1 text-xs text-slate-600"}>{active ? "Active" : "Inactive"}</span>; }
function Card({ title, badge, children }: { title: string; badge?: string; children: React.ReactNode }) { return <section className="min-h-44 rounded-xl border border-slate-200 p-5 shadow-sm"><div className="mb-6 flex items-center gap-2"><h3 className="text-lg font-semibold text-slate-950">{title}</h3>{badge && <span className="rounded-lg border border-slate-200 px-2 py-0.5 text-xs">{badge}</span>}</div>{children}</section>; }
function InfoGrid({ items, status }: { items: [string, string][]; status?: boolean }) { return <div className="grid grid-cols-3 gap-3">{items.map(([label, value]) => <div key={label}><p className="mb-2 text-slate-500">{label}:</p>{label === "Status" ? <Status active={Boolean(status)} /> : <p className="font-medium text-slate-900">{value}</p>}</div>)}</div>; }
function Value({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div><p className="mb-2 flex items-center gap-2 text-slate-500"><span className="size-4">{icon}</span>{label}</p><p className="font-medium text-slate-900">{value}</p></div>; }
function Guard({ name, index }: { name: string; index: number }) { const initials = name.split(" ").map((part) => part[0]).slice(0, 2).join(""); const role = index % 3 === 1 ? "OM" : "OFFICER"; return <div className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><span className="grid size-10 place-items-center rounded-full bg-blue-600 font-medium text-white">{initials}</span><div><p className="font-medium">{name} <span className={role === "OM" ? "ml-1 rounded-md border border-purple-200 bg-purple-50 px-2 py-0.5 text-xs text-purple-600" : "ml-1 rounded-md border border-blue-200 bg-blue-50 px-2 py-0.5 text-xs text-blue-600"}>{role}</span></p><p className="text-slate-500">ID: {name.replaceAll(" ", "")}{index + 1}</p></div></div>; }
function Activity({ label, date, green = false }: { label: string; date: string; green?: boolean }) { return <div className="rounded-xl border border-slate-200 p-3"><p className="flex items-center gap-3 font-medium"><span className={`size-2.5 rounded-full ${green ? "bg-emerald-500" : "bg-blue-500"}`} />{label}</p><p className="ml-5 mt-1 text-xs text-slate-500">{date}</p></div>; }
