import { Mail, MapPin, Phone, UserRoundCheck } from "lucide-react";
import type { DemoUser } from "./types";
import { UserActionsMenu } from "./UserActionsMenu";

export function UsersTable({ users, openMenuId, onToggleMenu, onCloseMenu }: { users: DemoUser[]; openMenuId: string | null; onToggleMenu: (id: string) => void; onCloseMenu: () => void }) {
  return <div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="border-b border-slate-200 text-left text-slate-900"><tr><th className="px-3 py-4 font-medium">User ↕</th><th className="px-3 py-4 font-medium">Contact</th><th className="px-3 py-4 font-medium">Role ↕</th><th className="px-3 py-4 font-medium">Assigned Site</th><th className="px-3 py-4 font-medium">Status ↕</th><th className="px-3 py-4 text-right font-medium">Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-slate-200 last:border-b-0"><td className="px-3 py-3"><div className="flex items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-blue-100 text-base text-blue-600">{user.name[0]}</span><div><p className="font-semibold text-slate-800">{user.name}</p><p className="mt-0.5 text-slate-500">ID: {user.id}</p></div></div></td><td className="px-3 py-3 text-slate-500"><p className="flex items-center gap-2"><Mail className="size-3.5" />{user.email || "-"}</p><p className="mt-1 flex items-center gap-2"><Phone className="size-3.5" />{user.phone}</p></td><td className="px-3 py-3"><span className={`inline-flex rounded-lg border px-2.5 py-1 text-xs font-medium ${user.role === "OM" ? "border-purple-200 bg-purple-50 text-purple-600" : "border-blue-200 bg-blue-50 text-blue-600"}`}>{user.role === "OM" ? "OM" : "OFFICER"}</span></td><td className="px-3 py-3 text-slate-500"><span className="flex items-center gap-2"><MapPin className="size-4 shrink-0" />{user.assignedSite ? `${user.assignedSite}${user.additionalSites ? " (+1 more)" : ""}` : "Unassigned"}</span></td><td className="px-3 py-3"><span className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-xs font-medium ${user.status === "ACTIVE" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}><UserRoundCheck className="size-3.5" />{user.status}</span></td><td className="px-3 py-3 text-right"><UserActionsMenu open={openMenuId === user.id} onToggle={() => onToggleMenu(user.id)} onClose={onCloseMenu} /></td></tr>)}</tbody></table>{users.length === 0 && <p className="py-12 text-center text-sm text-slate-500">No users found.</p>}</div>;
}

export function UsersTableSkeleton() { return <div className="animate-pulse"><div className="grid grid-cols-[1.6fr_1.4fr_0.8fr_1.5fr_0.8fr_0.4fr] gap-5 border-b border-slate-200 px-3 py-4">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-4 rounded bg-slate-100" />)}</div>{Array.from({ length: 7 }).map((_, row) => <div key={row} className="grid grid-cols-[1.6fr_1.4fr_0.8fr_1.5fr_0.8fr_0.4fr] gap-5 border-b border-slate-100 px-3 py-5">{Array.from({ length: 6 }).map((__, index) => <div key={index} className="h-5 rounded bg-slate-100" />)}</div>)}</div>; }
