"use client";

import { AlertTriangle, BookOpen, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, FileText, LayoutDashboard, MapPin, Megaphone, QrCode, Route, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

const links = [["Dashboard", "/om/dashboard", LayoutDashboard], ["Sites", "/om/sites", MapPin], ["Users", "/om/users", Users], ["Shift", "/om/shift", CalendarDays], ["Key Employment Term", "/om/key-employment-term", FileText], ["Incidents", "/om/incidents", AlertTriangle], ["Announcement", "/om/announcement", Megaphone], ["Occurrence Book", "/om/occurrence-book", BookOpen], ["Checkpoints", "/om/checkpoints", QrCode], ["Patrol Routes", "/om/patrol-routes", Route], ["Visitors", "/om/visitors", Users], ["Vehicles", "/om/vehicles", Route]] as const;
type IconType = typeof LayoutDashboard;
function NavLink({ collapsed, active, href, label, Icon }: { collapsed: boolean; active: boolean; href: string; label: string; Icon: IconType }) { return <Link href={href} title={collapsed ? label : undefined} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${active ? "bg-blue-50 font-semibold text-blue-600" : "text-slate-600 hover:bg-slate-100"}`}><Icon className="size-5 shrink-0" />{!collapsed && <span>{label}</span>}</Link>; }
export function OperationsSidebar() { const pathname = usePathname(); const [collapsed, setCollapsed] = useState(false); const [hrOpen, setHrOpen] = useState(pathname.startsWith("/om/hr")); const active = (href: string) => pathname === href; return <aside className={`sticky top-0 hidden h-screen shrink-0 border-r border-slate-200 bg-white transition-[width] duration-200 lg:block ${collapsed ? "w-20" : "w-64"}`}><div className="flex h-20 items-center border-b border-slate-200 px-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-blue-600 text-white"><ShieldCheck className="size-6" /></span>{!collapsed && <span className="ml-3 text-xl font-bold text-slate-800">Azovis</span>}<button onClick={() => setCollapsed((value) => !value)} className="ml-auto grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}>{collapsed ? <ChevronRight className="size-5" /> : <ChevronLeft className="size-5" />}</button></div><nav className="space-y-1 p-3">{links.slice(0, 4).map(([label, href, Icon]) => <NavLink key={href} collapsed={collapsed} active={active(href)} href={href} label={label} Icon={Icon} />)}<button onClick={() => setHrOpen((value) => !value)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${pathname.startsWith("/om/hr") ? "bg-blue-50 font-semibold text-blue-600" : "text-slate-600 hover:bg-slate-100"}`}><Users className="size-5 shrink-0" />{!collapsed && <><span>HR</span><ChevronDown className={`ml-auto size-4 transition ${hrOpen ? "rotate-180" : ""}`} /></>}</button>{hrOpen && !collapsed && <Link href="/om/hr/attendance" className={`ml-8 flex rounded-lg px-3 py-2 text-sm ${active("/om/hr/attendance") ? "font-semibold text-blue-600" : "text-slate-500 hover:bg-slate-100"}`}>Attendance</Link>}{links.slice(4).map(([label, href, Icon]) => <NavLink key={href} collapsed={collapsed} active={active(href)} href={href} label={label} Icon={Icon} />)}</nav><div className="absolute bottom-0 w-full border-t border-slate-200 p-4">{collapsed ? <span className="grid size-9 place-items-center rounded-full bg-blue-600 text-sm font-semibold text-white">E</span> : <div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-blue-600 text-sm font-semibold text-white">E</span><div><p className="text-sm font-semibold">Eaint (OM)</p><p className="text-xs text-slate-500">EOM01K</p></div></div>}</div></aside>; }
