import type { AttendanceEmployee, AttendanceFormValues, AttendanceRecord, AttendanceSite } from "./types";
const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";
type Result = { records: AttendanceRecord[]; stats: { total: number; onDuty: number; completed: number } };
const request = async <T>(path: string, options?: RequestInit) => { const response = await fetch(`${apiBaseUrl}${path}`, { ...options, headers: { "Content-Type": "application/json", ...options?.headers } }); if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.message ?? "Unable to complete the request."); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; };
export const getAttendance = (month: string, employeeId: string, query: string) => request<Result>(`/api/attendance?month=${encodeURIComponent(month)}&employeeId=${encodeURIComponent(employeeId)}&query=${encodeURIComponent(query)}`);
export const createAttendance = (payload: Partial<AttendanceFormValues>) => request<AttendanceRecord>("/api/attendance", { method: "POST", body: JSON.stringify(payload) });
export const updateAttendance = (id: string, payload: Partial<AttendanceFormValues>) => request<AttendanceRecord>(`/api/attendance/${id}`, { method: "PUT", body: JSON.stringify(payload) });
export const deleteAttendance = (id: string) => request<void>(`/api/attendance/${id}`, { method: "DELETE" });
export const getAttendanceEmployees = async () => (await request<{ employeeId: string; fullName: string }[]>("/api/users")).map((user) => ({ employeeId: user.employeeId, fullName: user.fullName })) satisfies AttendanceEmployee[];
export const getAttendanceSites = () => request<AttendanceSite[]>("/api/sites");
