"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createAttendance, deleteAttendance, getAttendance, getAttendanceEmployees, getAttendanceSites, updateAttendance } from "./attendance.api";
import { AttendanceFormModal } from "./AttendanceFormModal";
import { AttendanceStats } from "./AttendanceStats";
import { AttendanceTable } from "./AttendanceTable";
import { AttendanceToolbar } from "./AttendanceToolbar";
import type { AttendanceEmployee, AttendanceFormValues, AttendanceRecord, AttendanceSite } from "./types";

const monthKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
const shiftMonth = (month: string, amount: number) => { const [year, index] = month.split("-").map(Number); return monthKey(new Date(year, index - 1 + amount, 1)); };
const monthLabel = (month: string) => new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric" }).format(new Date(`${month}-01T00:00:00`));

export function AttendanceManagement() {
  const [month, setMonth] = useState(monthKey(new Date())); const [employeeId, setEmployeeId] = useState(""); const [query, setQuery] = useState("");
  const [records, setRecords] = useState<AttendanceRecord[]>([]); const [stats, setStats] = useState({ total: 0, onDuty: 0, completed: 0 }); const [employees, setEmployees] = useState<AttendanceEmployee[]>([]); const [sites, setSites] = useState<AttendanceSite[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [toast, setToast] = useState(""); const [editing, setEditing] = useState<AttendanceRecord | null | "new">(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await getAttendance(month, employeeId, query); setRecords(result.records); setStats(result.stats); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load attendance."); } finally { setLoading(false); } }, [employeeId, month, query]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { Promise.all([getAttendanceEmployees(), getAttendanceSites()]).then(([users, siteRows]) => { setEmployees(users); setSites(siteRows); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load form options.")); }, []);
  useEffect(() => { if (!toast) return; const timeout = window.setTimeout(() => setToast(""), 2800); return () => window.clearTimeout(timeout); }, [toast]);
  const save = async (values: Partial<AttendanceFormValues>) => { const record = editing !== "new" ? editing : null; if (record) await updateAttendance(record.id, values); else await createAttendance(values); setEditing(null); await load(); setToast(record ? "Attendance record updated." : "Attendance record added."); };
  const remove = async (record: AttendanceRecord) => { if (!window.confirm(`Delete attendance for ${record.employeeName}?`)) return; try { await deleteAttendance(record.id); await load(); setToast("Attendance record deleted."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete attendance record."); } };
  const exportRows = () => { const header = "Employee ID,Employee,Site,Date,Shift,Check In,Check Out,Status"; const rows = records.map((record) => [record.employeeId, record.employeeName, record.siteName ?? "", record.shiftDate.slice(0, 10), `${record.shiftStart}-${record.shiftEnd}`, record.checkInAt ?? "", record.checkOutAt ?? "", record.status].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([[header, ...rows].join("\n")], { type: "text/csv" })); link.download = `attendance-${month}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const shownStats = useMemo(() => stats, [stats]);
  return <main className="min-w-0 flex-1 overflow-x-hidden overflow-y-auto"><div className="min-w-0 px-5 pb-5 pt-2 text-slate-800"><div className="space-y-6"><header className="flex items-center justify-between gap-4"><div className="flex flex-col gap-2"><h1 className="text-2xl font-semibold text-slate-800">Attendance</h1><p className="text-sm text-slate-500">Monthly attendance overview for officers and operations managers.</p></div><div className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2"><button type="button" aria-label="Previous month" onClick={() => setMonth((value) => shiftMonth(value, -1))} className="grid size-8 place-items-center rounded-md hover:bg-slate-100"><ChevronLeft className="size-4" /></button><span className="min-w-[120px] text-center text-sm font-medium text-slate-900">{monthLabel(month)}</span><button type="button" aria-label="Next month" onClick={() => setMonth((value) => shiftMonth(value, 1))} className="grid size-8 place-items-center rounded-md hover:bg-slate-100"><ChevronRight className="size-4" /></button></div></header><AttendanceStats {...shownStats} /><section className="space-y-4"><AttendanceToolbar employees={employees} employeeId={employeeId} query={query} busy={loading} onEmployee={setEmployeeId} onQuery={setQuery} onRefresh={() => void load()} onAdd={() => setEditing("new")} onExport={exportRows} />{error && <p role="alert" className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<section className="flex min-h-[640px] flex-col overflow-hidden rounded-xl border border-slate-200 bg-white py-6 shadow-sm">{loading ? <p className="grid min-h-[560px] place-items-center text-sm text-slate-500">Loading attendance...</p> : <AttendanceTable records={records} onEdit={setEditing} onDelete={(record) => void remove(record)} />}</section></section></div></div>{toast && <div role="status" className="fixed right-5 top-5 z-[60] rounded-lg bg-emerald-600 px-4 py-3 text-sm font-medium text-white shadow-lg">{toast}</div>}{editing && <AttendanceFormModal key={editing === "new" ? "new" : editing.id} record={editing === "new" ? null : editing} employees={employees} sites={sites} onClose={() => setEditing(null)} onSave={save} />}</main>;
}
