"use client";

import { Eye, EyeOff, LockKeyhole, X } from "lucide-react";
import { useState } from "react";

type PasswordValues = { currentPassword: string; newPassword: string; confirmPassword: string };
const blank: PasswordValues = { currentPassword: "", newPassword: "", confirmPassword: "" };

export function ChangePasswordModal({ saving, onClose, onSave }: { saving: boolean; onClose: () => void; onSave: (values: PasswordValues) => Promise<void> }) {
  const [values, setValues] = useState(blank); const [show, setShow] = useState<Record<keyof PasswordValues, boolean>>({ currentPassword: false, newPassword: false, confirmPassword: false }); const [error, setError] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(null); if (values.newPassword !== values.confirmPassword) { setError("New password and confirmation do not match."); return; } try { await onSave(values); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to change password."); } };
  const fields: Array<[keyof PasswordValues, string, string]> = [["currentPassword", "Current Password", "Enter current password"], ["newPassword", "New Password", "Enter new password"], ["confirmPassword", "Confirm New Password", "Confirm new password"]];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><form onSubmit={submit} className="w-full max-w-3xl rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><header className="flex items-center justify-between"><h2 className="flex items-center gap-3 text-xl font-bold text-slate-900"><LockKeyhole className="size-6 text-blue-600" />Change Password</h2><button type="button" onClick={onClose} className="rounded-md p-1 text-slate-500 hover:bg-slate-100" aria-label="Close password dialog"><X className="size-5" /></button></header><div className="mt-6 space-y-4">{fields.map(([name, label, placeholder]) => <label key={name} className="block"><span className="mb-2 block text-sm font-medium text-slate-800">{label} <b className="text-red-500">*</b></span><span className="relative block"><input required value={values[name]} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} type={show[name] ? "text" : "password"} placeholder={placeholder} className="h-12 w-full rounded-xl border border-slate-200 px-4 pr-12 text-sm outline-none transition placeholder:text-slate-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-100" /><button type="button" onClick={() => setShow((current) => ({ ...current, [name]: !current[name] }))} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600" aria-label={show[name] ? "Hide password" : "Show password"}>{show[name] ? <EyeOff className="size-5" /> : <Eye className="size-5" />}</button></span></label>)}</div>{error && <p className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<footer className="mt-8 flex justify-between gap-3"><button type="button" onClick={onClose} className="h-11 rounded-xl border border-slate-200 px-7 text-sm font-medium hover:bg-slate-50">Cancel</button><button disabled={saving} type="submit" className="h-11 rounded-xl bg-neutral-900 px-7 text-sm font-medium text-white disabled:opacity-60">{saving ? "Saving..." : "Save Changes"}</button></footer></form></div>;
}
