export type UserInput = {
  fullName: string;
  employeeId: string;
  company?: string;
  nric?: string;
  employmentType?: string;
  password?: string;
  profileImageUrl?: string;
  dateOfBirth?: string;
  nationality: string;
  gender?: string;
  race?: string;
  religion?: string;
  phone: string;
  email?: string;
  nfcCode?: string;
  maritalStatus?: string;
  address?: string;
  role: string;
  secondaryRole?: string;
  insurancePlan?: string;
  primaryNokName?: string;
  primaryNokRelationship?: string;
  primaryNokLanguage?: string;
  primaryNokPhone?: string;
  secondaryNokName?: string;
  secondaryNokRelationship?: string;
  secondaryNokLanguage?: string;
  secondaryNokPhone?: string;
  vaccinated?: boolean | "Yes" | "No";
  bypassGpsGeofence?: boolean;
  deploymentSiteId?: string;
  siteIds?: string[];
};
